name = "flipper-clippers"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Custom domain
routes = [
  { pattern = "flipper-clippers.arross.tv", custom_domain = true }
]

# Static assets from public folder
[assets]
directory = "public"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "clip-ranker-db"
database_id = "7154d07b-e848-402a-a4e7-df008883bad4"

[vars]
TWITCH_CLIENT_ID = "bcsrqxz7j1ivepc5g2bfnreok2x2g0"
